
[theme]
base="light"
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"

[theme.dark]
base="dark"
primaryColor="#00FFAA"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FFFFFF"
font="sans serif"
